// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0akU7Ziu-uIS93tUWV09k1ZHlrzRwAQI',
    appId: '1:368834360078:android:5ebc31daf67c3a0ffb5d5f',
    messagingSenderId: '368834360078',
    projectId: 'fccapp-84298',
    storageBucket: 'fccapp-84298.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNpa_n1_Gvha_rC100TRGSRYluu0GKcUI',
    appId: '1:368834360078:ios:76dfb07897496e98fb5d5f',
    messagingSenderId: '368834360078',
    projectId: 'fccapp-84298',
    storageBucket: 'fccapp-84298.appspot.com',
    iosClientId: '368834360078-p9r2ft506e74l3q6t11h7r5jst7av4pi.apps.googleusercontent.com',
    iosBundleId: 'com.aryaman.fcc',
  );
}
